### ISSUE TITLE
Lint issues

### ISSUE THREAD

**Issue by drgrigg** [mclow/arthur-conan-doyle_the-case-book-of-sherlock-holmes#1]
Production notes are still missing (if none, this entry in content.opf should be removed).

core.css doesn't match the current version, you just need to update to the current toolset and copy across the template.

Also, not a lint issue, but se clean makes a minor change which should be accepted.

**Comment by mclow** [comment]
I'm not sure if I will put anything there; so I left it.  I'll decide before I give it back for review again.  I removed the blank lines at the end of the colophon in commit 9a18191
