### ISSUE TITLE
Case-Book or Casebook?

### ISSUE THREAD

**Issue by drgrigg** [mclow/arthur-conan-doyle_the-case-book-of-sherlock-holmes#3]
Was a decision made to preserve the separated words? 

Modernize-spelling wants to make it Casebook, and I don't see much reason not to change it throughout, though it would have be an editorial change, of course, and you'd have to adjust the titlepage, colophon, etc., which would be a pain. 

If you have strong feelings against this change we might need to consult Alex.

**Comment by drgrigg** [comment]
Actually it was build-toc which wanted to change it.

**Comment by drgrigg** [comment]
And I see that content.opf has it as one word. I think we need to standardise on the single word version.

**Comment by mclow** [comment]
There are actually three choices here:
* Case-Book
* Casebook
* Case Book

The page scans show "Case Book".
The transcription from the Internet Archive uses "Casebook"
[Wikipedia](https://en.wikipedia.org/wiki/The_Case-Book_of_Sherlock_Holmes) uses "Case-Book"

I agree - we should pick one and stick with it.

**Comment by mclow** [comment]
After discussion on the ML, we settled on "Casebook / casebook"
