### ISSUE TITLE
Italics need to be semanticated

### ISSUE THREAD

**Issue by drgrigg** [mclow/arthur-conan-doyle_the-case-book-of-sherlock-holmes#4]
You need to add semantic inflection to all the bare `<i>` tags in your text, marking them as books, newspapers, etc as appropriate. 

Check out this section of the manual: https://standardebooks.org/manual/1.7.0/single-page#8.2.11.2 .

You also have an instance of taxonomy which needs to be semanticated: `<i>Cyanea capillata</i>`as `<i epub:type="z3998:taxonomy">Cyanea capillata</i>`

**Comment by drgrigg** [comment]
For books, newspapers, etc, we use the SE vocabulary here: https://standardebooks.org/vocab/1.0

**Comment by drgrigg** [comment]
Only one problem here: the Lancet and Medical Journal should be marked as se:name.publication.journal, not magazine.

**Comment by mclow** [comment]
Addressed in c997a6e
