### ISSUE TITLE
[Editorial] commits don't need to be marked [Editorial]

### ISSUE THREAD

**Issue by drgrigg** [mclow/arthur-conan-doyle_the-case-book-of-sherlock-holmes#5]
Your commit `[Editorial] 'se clean' changes` (commit e205092f8498d03c598fa877362ef7491d0704d7) . SE clean doesn't require to be [Editorial]. 

Similarly commit 5db89204dba492cd466385ec6ed7049dc1e65bc2.

Neither does the renaming of the chapter files (commit 6b6e7b55de3bfa91f4a299b32c29541d19dcd8e8).

In general, we need [Editorial] where we are changing the text from what is in the page scans, because of an editorial decision on our part, but neither of these qualifies.

Because we want to reserve the [Editorial] tags just for commits which are indeed editorial decisions, you should rebase your repository and remove the tags from the above commits. If you haven't used git rebase before, let me know and I can walk you through the process, it's quite easy for this kind of renaming task.

**Comment by mclow** [comment]
Fixed.
